# action.yml
name: 'Get POS CI Instance URL'
description: 'populate env with ci-instance-url and report-url variables'
inputs:
  method:  # id of input
    description: 'method to execute. either reserve or release'
    required: true
    default: 'reserve'
  repository-url:  # id of input
    description: 'url of the instance repository'
    required: true
  pos-ci-repo-token:  # id of input
    description: 'pos cli ci repo access token'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.method }}
    - ${{ inputs.repository-url }}
    - ${{ inputs.pos-ci-repo-token }}
